"use client";

import type { FormEvent } from "react";
import { RefreshCw, X } from "lucide-react";
import { CameraSnapshot } from "@/app/resident/camera-snapshot";
import { formatTime, spacedPin, type CameraView, type GuestCode, type PermanentCode } from "@/app/resident/model";

export function CameraDialog({ camera, revision, configured, updatedAt, refreshing, onSettled, onRefresh, onClose }: { camera: CameraView; revision: number; configured: boolean; updatedAt: Date; refreshing: boolean; onSettled: (camera: CameraView, revision: number, loaded: boolean) => void; onRefresh: () => void; onClose: () => void }) {
  const label = camera === "person" ? "Person" : "Road";
  return <div className="resident-dialog-backdrop" role="presentation"><section className="resident-dialog resident-camera-dialog" role="dialog" aria-modal="true" aria-labelledby="camera-dialog-title">
    <div className="resident-dialog-heading"><div><p className="resident-kicker">Camera snapshot</p><h2 id="camera-dialog-title">{camera === "person" ? "Person at the call box" : "Road-facing camera"}</h2></div><button type="button" onClick={onClose} aria-label="Close"><X aria-hidden="true" /></button></div>
    <div className={`resident-camera-large resident-camera-${camera}`}><CameraSnapshot camera={camera} label={label} revision={revision} configured={configured} onSettled={onSettled} /></div>
    <div className="resident-camera-dialog-footer"><span>Refreshed {formatTime(updatedAt)}</span><button className="resident-secondary-button" type="button" onClick={onRefresh} disabled={refreshing}><RefreshCw className={refreshing ? "spinning" : ""} aria-hidden="true" />{refreshing ? "Refreshing" : "Refresh"}</button></div>
  </section></div>;
}

export function PartyDialog({ pending, startChoice, startTime, endTime, error, onStartChoiceChange, onStartTimeChange, onEndTimeChange, onSubmit, onClose }: { pending: boolean; startChoice: "now" | "later"; startTime: string; endTime: string; error: string; onStartChoiceChange: (choice: "now" | "later") => void; onStartTimeChange: (value: string) => void; onEndTimeChange: (value: string) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onClose: () => void }) {
  return <div className="resident-dialog-backdrop" role="presentation"><section className="resident-dialog" role="dialog" aria-modal="true" aria-labelledby="party-dialog-title">
    <div className="resident-dialog-heading"><div><p className="resident-kicker">Today only</p><h2 id="party-dialog-title">Set up party mode</h2></div><button type="button" disabled={pending} onClick={onClose} aria-label="Close"><X aria-hidden="true" /></button></div>
    <p className="resident-dialog-intro">The gate will stay open so guests can drive in freely.</p>
    <form onSubmit={onSubmit}><fieldset className="resident-choice-fieldset" disabled={pending}><legend>Starts</legend><label className={startChoice === "now" ? "selected" : ""}><input type="radio" name="party-start" checked={startChoice === "now"} onChange={() => onStartChoiceChange("now")} /><strong>Now</strong><span>Open the gate right away</span></label><label className={startChoice === "later" ? "selected" : ""}><input type="radio" name="party-start" checked={startChoice === "later"} onChange={() => onStartChoiceChange("later")} /><strong>Later today</strong><span>Choose a starting time</span></label></fieldset>{startChoice === "later" ? <label className="resident-time-field">Gate opens<input type="time" value={startTime} onChange={(event) => onStartTimeChange(event.target.value)} required disabled={pending} /></label> : null}<label className="resident-time-field">Gate closes<input type="time" value={endTime} onChange={(event) => onEndTimeChange(event.target.value)} required disabled={pending} /></label>{error ? <p className="resident-form-error" role="alert">{error}</p> : null}<button className="resident-primary-button" type="submit" disabled={pending}>{pending ? "Setting up…" : startChoice === "now" ? "Start party mode" : "Schedule party mode"}</button></form>
  </section></div>;
}

export function GateCodeDialog({ mode, householdName, householdCode, name, pin, error, onNameChange, onPinChange, onSubmit, onClose }: { mode: "household" | "person"; householdName: string; householdCode?: PermanentCode; name: string; pin: string; error: string; onNameChange: (value: string) => void; onPinChange: (value: string) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onClose: () => void }) {
  return <div className="resident-dialog-backdrop" role="presentation"><section className="resident-dialog" role="dialog" aria-modal="true" aria-labelledby="code-dialog-title">
    <div className="resident-dialog-heading"><div><p className="resident-kicker">Gate code</p><h2 id="code-dialog-title">{mode === "household" ? `${householdCode ? "Change" : "Set"} ${householdName} gate code` : "Add ongoing code"}</h2></div><button type="button" onClick={onClose} aria-label="Close"><X aria-hidden="true" /></button></div>
    <p className="resident-dialog-intro">{mode === "household" ? "Everyone in your household can use this at the keypad." : "Use this for Sarah, a gardener, deliveries, or anyone else who should always be able to enter."}</p>
    <form onSubmit={onSubmit}>{mode === "person" ? <label className="resident-field-label" htmlFor="permanent-name">What is this for?<input id="permanent-name" className="resident-input" value={name} onChange={(event) => onNameChange(event.target.value)} placeholder="For example, Sarah or Gardener" autoFocus /></label> : null}<label className="resident-field-label" htmlFor="permanent-pin">Choose a gate code <span>4–6 numbers</span><input id="permanent-pin" className="resident-input resident-pin-input" value={pin} onChange={(event) => onPinChange(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="off" placeholder="4826" autoFocus={mode === "household"} /></label>{error ? <p className="resident-form-error" role="alert">{error}</p> : null}<button className="resident-primary-button" type="submit">{mode === "household" ? "Save gate code" : "Add code"}</button></form>
  </section></div>;
}

export function CancelCodeDialog({ code, onConfirm, onClose }: { code: GuestCode; onConfirm: () => void; onClose: () => void }) {
  return <div className="resident-dialog-backdrop" role="presentation"><section className="resident-dialog" role="alertdialog" aria-modal="true" aria-labelledby="cancel-title"><p className="resident-kicker">Please confirm</p><h2 id="cancel-title">Cancel {code.label}&apos;s code?</h2><p className="resident-dialog-intro">The code <strong>{spacedPin(code.pin)}</strong> will stop working right away.</p><div className="resident-dialog-actions"><button className="resident-danger-button" type="button" onClick={onConfirm}>Yes, cancel code</button><button className="resident-secondary-button" type="button" onClick={onClose}>Keep it active</button></div></section></div>;
}

export function ExpireCodeDialog({ code, pending, error, onConfirm, onClose }: { code: PermanentCode; pending: boolean; error: string; onConfirm: () => void; onClose: () => void }) {
  return <div className="resident-dialog-backdrop" role="presentation"><section className="resident-dialog" role="alertdialog" aria-modal="true" aria-labelledby="expire-title"><p className="resident-kicker">Please confirm</p><h2 id="expire-title">Expire {code.label}?</h2><p className="resident-dialog-intro">The ongoing code <strong>{spacedPin(code.pin)}</strong> will stop working right away. This cannot be undone.</p>{error ? <p className="resident-form-error" role="alert">{error}</p> : null}<div className="resident-dialog-actions"><button className="resident-danger-button" type="button" disabled={pending} onClick={onConfirm}>{pending ? "Expiring…" : "Yes, expire code"}</button><button className="resident-secondary-button" type="button" disabled={pending} onClick={onClose}>Keep it active</button></div></section></div>;
}

export function PasswordDialog({ currentPassword, newPassword, confirmation, pending, error, success, onCurrentPasswordChange, onNewPasswordChange, onConfirmationChange, onSubmit, onClose }: { currentPassword: string; newPassword: string; confirmation: string; pending: boolean; error: string; success: string; onCurrentPasswordChange: (value: string) => void; onNewPasswordChange: (value: string) => void; onConfirmationChange: (value: string) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onClose: () => void }) {
  return <div className="resident-dialog-backdrop" role="presentation"><section className="resident-dialog" role="dialog" aria-modal="true" aria-labelledby="password-title">
    <div className="resident-dialog-heading"><div><p className="resident-kicker">Account security</p><h2 id="password-title">Change password</h2></div><button type="button" onClick={onClose} aria-label="Close"><X aria-hidden="true" /></button></div>
    <form className="resident-password-form" onSubmit={onSubmit}><label>Current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={(event) => onCurrentPasswordChange(event.target.value)} required autoFocus /></label><label>New password<input type="password" autoComplete="new-password" minLength={8} maxLength={128} value={newPassword} onChange={(event) => onNewPasswordChange(event.target.value)} required /></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength={8} maxLength={128} value={confirmation} onChange={(event) => onConfirmationChange(event.target.value)} required /></label>{error ? <p className="resident-form-error" role="alert">{error}</p> : null}{success ? <p className="resident-form-success" role="status">{success}</p> : null}<button className="resident-primary-button" type="submit" disabled={pending}>{pending ? "Changing password…" : "Change password"}</button></form>
  </section></div>;
}
